import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {parsePine,evaluatePine,setPineInput,setPinePlotColor,setPineFillColor,cleanPine,type OnchainData} from "../lib/pine";
import { values,type Bar } from "../lib/indicators";
const bars:Bar[]=Array.from({length:100},(_,i)=>({time:(200+i)*86400,open:i,high:i+2,low:i-2,close:i,volume:100}));
const simple=parsePine('//@version=6\nindicator("test", overlay=true)\nn = input.int(5)\nplot(ta.sma(close,n), color=color.red)\nplot(ta.ema(close,n))\nplot(ta.rsi(close,n))\nplot(ta.stdev(close,n))');
assert.deepEqual(evaluatePine(bars,simple,"1d").plots, ["sma","ema","rsi","stdev"].map(kind=>values(bars,{kind:kind as "sma"|"ema"|"rsi"|"stdev",field:"close",length:5})));
assert.throws(()=>parsePine('indicator("test")\nplot(fetch("https://evil.test"))'),/Dòng 2.*fetch/);
assert.throws(()=>parsePine('plot(request.security("NASDAQ:AAPL", "D", close, barmerge.gaps_off, barmerge.lookahead_off))'),/Dòng 1.*nguồn/);
assert.throws(()=>parsePine('plot(close, offset=10)'),/offset/);
assert.throws(()=>parsePine('x := 2\nplot(x)'),/chưa khai báo/);
const source=readFileSync("examples/pine/btc-cost-of-production.pine","utf8");
const f=parsePine(source);assert.equal(f.requests.length,5);assert.equal(f.plots.length,3);assert.equal(f.fills.length,1);assert.equal(f.plots[2].opacity,0);assert.ok(Math.abs(f.fills[0].opacity-.4)<1e-12);assert.equal(f.priceDependent,false);
const pasted=source.split("\n").map(x=>`**${x.replace(/\*/g,"\\*").replace(/^    /,"&#xA0;    ")}**`).join("\n");assert.deepEqual(parsePine(pasted).plots,f.plots);assert.ok(!cleanPine(pasted).includes("&#xA0;"));
const edited=setPinePlotColor(source,2,"#123456");assert.equal(parsePine(edited).plots[2].color,"#123456");assert.equal(parsePine(edited).plots[2].opacity,0);assert.ok(edited.includes("© jv_indicators"));
const fillEdit=parsePine(setPineFillColor(source,0,"#abcdef"));assert.equal(fillEdit.fills[0].color,"#abcdef");assert.ok(Math.abs(fillEdit.fills[0].opacity-.4)<1e-12);
const data:OnchainData={rows:Array.from({length:350},(_,i)=>({time:i*86400,difficulty:1e14,feesUsd:10000,priceUsd:50000,blocks:144,height:850000})),updatedAt:"",sources:[]};
const result=evaluatePine(bars,f,"1d",data);const expected=(1/1800)*Math.pow(1e14,.45)/(3.125*144+10000/50000);
assert.ok(result.plots[0].every(v=>v!==null&&Math.abs(v-expected)<1e-8));assert.ok(result.plots[1].every(v=>v===null));assert.ok(result.plots[2].every(v=>v!==null&&Math.abs(v-expected*1.2)<1e-8));
const raw=parsePine(setPineInput(setPineInput(source,"showRaw",true),"showSmoothed",false));const rr=evaluatePine(bars,raw,"1d",data);assert.ok(rr.plots[0].every(v=>v===null));assert.ok(rr.plots[1].every(v=>v!==null&&Math.abs(v-expected)<1e-8));
const hourly=[{...bars[0],time:200*86400+3600}];data.rows[200].feesUsd=99999999;const hf=parsePine(setPineInput(source,"showRaw",true));const hr=evaluatePine(hourly,hf,"1h",data);assert.ok(Math.abs(hr.plots[1][0]!-expected)<1e-8,"A daily value is not available before its day closes");
const changedBars=[{...hourly[0],close:123456}];assert.strictEqual(evaluatePine(changedBars,hf,"1h",data),hr,"On-chain only scripts do not recalculate on price ticks");
const minute=evaluatePine([{...bars[0],time:200*86400}],hf,"1m",data);assert.ok(minute.plots[0][0]!==null,"90-day smoothing warms up on 1m");
console.log("Pine: basic TA parity, complete script, Markdown paste, colors, switches, no lookahead, 1m warmup and rejection checks passed");
