"use client";
import Link from "next/link";
import { useEffect,useState,useRef,type FormEvent } from "react";
export default function AccountToken({purpose}:{purpose:"verify"|"reset"}) {
  const received=useRef<string|null>(null);
  const [token,setToken]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{const value=received.current ?? (new URLSearchParams(window.location.hash.slice(1)).get("token")||"");received.current=value;queueMicrotask(()=>{setToken(value);if(!value)setError("Thiếu liên kết xác nhận. Hãy mở liên kết trong email.");});window.history.replaceState(null,"",window.location.pathname);},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(purpose==="reset"&&password!==confirm){setError("Hai mật khẩu chưa khớp.");return;}setError("");setBusy(true);try{const r=await fetch("/api/account/recovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:purpose,token,password})});const d=await r.json() as {error:string;message:string};if(!r.ok)throw Error(d.error);setMessage(d.message);setPassword("");setConfirm("");setToken("");}catch(cause){setError(cause instanceof Error?cause.message:"Không xử lý được yêu cầu.");}finally{setBusy(false);}};
  return <main className="account-token-page"><section className="account-dialog"><span className="panel-eyebrow">CHART LAB</span><h2>{purpose==="reset"?"Đặt lại mật khẩu":"Xác minh email"}</h2>{message?<p className="account-success" role="status">{message}</p>:<form onSubmit={submit}>{purpose==="reset"&&<><label>Mật khẩu mới<input type="password" name="new-password" required minLength={10} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Nhập lại mật khẩu<input type="password" required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}{purpose==="verify"&&<p>Bấm xác nhận để gắn email trong thư vào tài khoản. Liên kết chỉ sử dụng một lần.</p>}<button className="account-submit" disabled={!token||busy}>{busy?"Đang xử lý…":purpose==="reset"?"Đổi mật khẩu":"Xác minh email"}</button></form>}{error&&<p className="account-error" role="alert">{error}</p>}<Link href="/" className="account-link">Về biểu đồ</Link></section></main>;
}
