"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, ChartCandlestick, ChevronDown, CircleHelp, Code2, Maximize2, RefreshCw, Settings2, Shield, Wifi, WifiOff, X } from "lucide-react";
import CandleChart from "./CandleChart";
import { parsePine, type Bar, type Formula } from "@/lib/indicators";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Script={id:string;name:string;source:string};
type Account={email:string;role:string;displayName:string};
const DEFAULT={ma:true,bb:false,rsi:true,volume:true};
const FRAMES=["1m","5m","15m","1h","4h","1d","1w"];
const SAMPLE='//@version=5\nindicator("MA cá nhân", overlay=true)\nlength = input.int(30)\nplot(ta.sma(close, length))';
const PALETTE=[{key:"ma",title:"Moving Average",detail:"SMA · 20",color:"#ffcc73"},{key:"bb",title:"Bollinger Bands",detail:"20 · 2σ",color:"#ad8ef8"},{key:"rsi",title:"RSI",detail:"14 kỳ",color:"#7daaff"},{key:"volume",title:"Volume",detail:"Khối lượng",color:"#29c1a1"}];
async function api(body:Record<string,unknown>){const r=await fetch("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json() as any;if(!r.ok)throw Error(data.error||"Thao tác thất bại");return data;}
export default function Workspace(){
 const [market,setMarket]=useState<"spot"|"futures">("spot"),[symbol,setSymbol]=useState("BTCUSDT"),[symbolDraft,setSymbolDraft]=useState("BTCUSDT"),[interval,setInterval]=useState("1h"),[enabled,setEnabled]=useState<Record<string,boolean>>(DEFAULT);
 const [bars,setBars]=useState<Bar[]>([]),[status,setStatus]=useState("Đang tải"),[error,setError]=useState(""),[hover,setHover]=useState<Bar|null>(null),[panel,setPanel]=useState<"indicators"|"editor"|"access"|"help">("indicators");
 const [me,setMe]=useState<Account|null>(null),[scripts,setScripts]=useState<Script[]>([]),[invites,setInvites]=useState<{email:string}[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
 const [scriptId,setScriptId]=useState<string|null>(null),[scriptName,setScriptName]=useState("Chỉ báo của tôi"),[source,setSource]=useState(SAMPLE),[activeScript,setActiveScript]=useState<string|null>(null),[formula,setFormula]=useState<Formula|null>(null),[email,setEmail]=useState("");
 const historyBusy=useRef(false),oldest=useRef(0),historyEnd=useRef(0),dataRef=useRef<Bar[]>([]);
 const shown=hover||bars[bars.length-1];
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),4500)};
 useEffect(()=>{fetch("/api/workspace").then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);setMe(d.me);setScripts(d.scripts||[]);setInvites(d.invites||[]);if(d.config){setMarket(d.config.market);setSymbol(d.config.symbol);setSymbolDraft(d.config.symbol);setInterval(d.config.interval);try{const saved=JSON.parse(d.config.enabled);setEnabled({...DEFAULT,...saved});if(saved._activeScript){const found=(d.scripts||[]).find((x:Script)=>x.id===saved._activeScript);if(found){setActiveScript(found.id);setFormula(parsePine(found.source))}}}catch{}}setReady(true)}).catch(e=>{setError(e.message||"Không tải được tài khoản");setReady(true)});},[]);
 useEffect(()=>{if(!ready||!me)return;const timer=setTimeout(()=>api({action:"saveSettings",market,symbol,interval,enabled:{...enabled,_activeScript:activeScript}}).catch(()=>flash("Chưa lưu được cấu hình")),800);return()=>clearTimeout(timer);},[ready,me,market,symbol,interval,enabled,activeScript]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;
  if(!ready||!me||!context?.registerTool)return;
  const controller=new AbortController();
  try{void Promise.resolve(context.registerTool({name:"configure_binance_chart",title:"Chọn biểu đồ Binance",description:"Chọn Spot hoặc Futures USDⓈ-M, cặp giao dịch và khung thời gian trên biểu đồ đang mở.",inputSchema:{type:"object",properties:{market:{type:"string",enum:["spot","futures"]},symbol:{type:"string",pattern:"^[A-Za-z0-9]{5,20}$"},interval:{type:"string",enum:FRAMES}},required:["market","symbol","interval"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as Record<string,unknown>;if(!["spot","futures"].includes(String(v.market))||!FRAMES.includes(String(v.interval))||!(/^[A-Z0-9]{5,20}$/).test(String(v.symbol).toUpperCase()))throw Error("Cặp hoặc khung không hợp lệ");await api({action:"saveSettings",market:v.market,symbol:String(v.symbol).toUpperCase(),interval:v.interval,enabled});setMarket(v.market as "spot"|"futures");setSymbol(String(v.symbol).toUpperCase());setSymbolDraft(String(v.symbol).toUpperCase());setInterval(String(v.interval));return {market:v.market,symbol:String(v.symbol).toUpperCase(),interval:v.interval}}},{signal:controller.signal})).catch(()=>{});}catch{}
  return()=>controller.abort();
 },[ready,me,enabled]);
 const load=useCallback(async(endTime?:number)=>{
  const query=new URLSearchParams({market,symbol,interval});if(endTime)query.set("endTime",String(endTime));
  const response=await fetch("/api/market?"+query);const data=await response.json() as any;if(!response.ok)throw Error(data.error||"Không tải được nến");return data.bars as Bar[];
 },[market,symbol,interval]);
 useEffect(()=>{if(!ready||!me)return;let closed=false;let ws:WebSocket|null=null;let retry:ReturnType<typeof setTimeout>|undefined;let poll:number|undefined;let count=0;dataRef.current=[];oldest.current=0;historyEnd.current=0;setBars([]);setHover(null);setStatus("Đang tải");setError("");
  const refresh=async()=>{try{const fresh=await load();if(closed)return;const merged=new Map<number,Bar>(dataRef.current.map(x=>[x.time,x]));fresh.forEach(x=>merged.set(x.time,x));dataRef.current=[...merged.values()].sort((a,b)=>a.time-b.time).slice(-1500);setBars(dataRef.current);setStatus("Đồng bộ định kỳ")}catch(e){if(!closed)setError((e as Error).message)}};
  const connect=()=>{if(closed)return;const stream=`${symbol.toLowerCase()}@kline_${interval}`;const base=market==="spot"?"wss://stream.binance.com:9443/ws/":"wss://fstream.binance.com/ws/";try{ws=new WebSocket(base+stream);ws.onopen=()=>{count=0;setStatus("Trực tiếp");setError("");if(poll){window.clearInterval(poll);poll=undefined}};ws.onmessage=event=>{try{const k=JSON.parse(event.data).k;if(!k||closed)return;const bar:Bar={time:Math.floor(Number(k.t)/1000),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v)};const a=dataRef.current;if(!a.length)return;if(bar.time===a[a.length-1].time)a[a.length-1]=bar;else if(bar.time>a[a.length-1].time)a.push(bar);else return;dataRef.current=[...a];setBars(dataRef.current)}catch{}};ws.onerror=()=>ws?.close();ws.onclose=()=>{if(closed)return;setStatus("Đang kết nối lại");if(!poll)poll=window.setInterval(refresh,15000);retry=setTimeout(connect,Math.min(30000,1500*2**Math.min(count++,5)))}}catch{setStatus("Đồng bộ định kỳ");if(!poll)poll=window.setInterval(refresh,15000);retry=setTimeout(connect,10000)}};
  load().then(initial=>{if(closed)return;dataRef.current=initial;setBars(initial);oldest.current=initial[0]?.time||0;setStatus("Đang kết nối");connect()}).catch(e=>{if(!closed){setError(e.message);setStatus("Không có dữ liệu")}});
  return()=>{closed=true;ws?.close();clearTimeout(retry);window.clearInterval(poll)};
 },[ready,me,load,market,symbol,interval]);
 const more=useCallback(async(endTime:number)=>{if(historyBusy.current||!oldest.current||endTime>=oldest.current*1000||historyEnd.current===endTime)return;historyBusy.current=true;historyEnd.current=endTime;try{const older=await load(endTime);if(older.length){const map=new Map<number,Bar>([...older,...dataRef.current].map(b=>[b.time,b]));dataRef.current=[...map.values()].sort((a,b)=>a.time-b.time).slice(-3000);oldest.current=dataRef.current[0].time;setBars([...dataRef.current])}}catch{flash("Chưa tải được nến cũ") }finally{historyBusy.current=false}},[load]);
 const active=useMemo(()=>scripts.find(s=>s.id===activeScript),[scripts,activeScript]);
 const toggle=(key:string)=>setEnabled(x=>({...x,[key]:!x[key]}));
 const apply=()=>{try{const f=parsePine(source);setFormula(f);setActiveScript(scriptId);flash("Đã áp dụng chỉ báo lên biểu đồ")}catch(e){flash((e as Error).message)}};
 const save=async()=>{try{parsePine(source);const d=await api({action:"saveScript",id:scriptId||undefined,name:scriptName,source});setScriptId(d.id);setScripts(x=>[{id:d.id,name:scriptName,source},...x.filter(s=>s.id!==d.id)]);setFormula(parsePine(source));setActiveScript(d.id);flash("Đã lưu và áp dụng chỉ báo")}catch(e){flash((e as Error).message)}};
 const remove=async()=>{if(!scriptId)return;try{await api({action:"deleteScript",id:scriptId});setScripts(x=>x.filter(s=>s.id!==scriptId));if(activeScript===scriptId){setActiveScript(null);setFormula(null)}setScriptId(null);setScriptName("Chỉ báo của tôi");setSource(SAMPLE);flash("Đã xóa chỉ báo")}catch(e){flash((e as Error).message)}};
 const addInvite=async()=>{try{await api({action:"invite",email});setInvites(x=>[...x.filter(v=>v.email!==email.toLowerCase()),{email:email.toLowerCase()}]);setEmail("");flash("Đã thêm vào danh sách; cần cấp quyền xem Site trong phần Chia sẻ của Sites") }catch(e){flash((e as Error).message)}};
 if(ready&&!me)return <main className="blocked"><Shield size={32}/><h1>Không thể mở biểu đồ</h1><p>{error||"Tài khoản của bạn chưa được cấp quyền."}</p></main>;
 return <main className="workspace">
  <header className="topbar"><div className="brand"><span className="brand-icon"><ChartCandlestick size={20}/></span><span>CHART<span className="brand-accent">LAB</span></span></div><span className="top-divider"/><span className="product-label">BINANCE MARKETS</span><div className="top-grow"/><span className={'status '+(status==="Trực tiếp"?'live':'')}>{status==="Trực tiếp"?<Wifi size={14}/>:<WifiOff size={14}/>} {status}</span><span className="account" title={me?.email}>{me?.email||"Đang xác thực"}</span></header>
  <div className="body-grid"><section className="main-column"><div className="toolbar"><div className="market-switch"><button className={market==="spot"?'selected':''} onClick={()=>setMarket("spot")}>Spot</button><button className={market==="futures"?'selected':''} onClick={()=>setMarket("futures")}>Futures USDⓈ-M</button></div><form className="symbol-form" onSubmit={e=>{e.preventDefault();const next=symbolDraft.trim().toUpperCase();if(/^[A-Z0-9]{5,20}$/.test(next))setSymbol(next);else flash("Mã cặp không hợp lệ")}}><Activity size={16}/><input aria-label="Cặp giao dịch Binance" value={symbolDraft} onChange={e=>setSymbolDraft(e.target.value.toUpperCase())}/><button title="Mở cặp">↵</button></form><div className="timeframes">{FRAMES.map(f=><button key={f} className={interval===f?'selected':''} onClick={()=>setInterval(f)}>{f}</button>)}</div><div className="toolbar-spacer"/><button className="icon-btn" onClick={()=>{setPanel("indicators")}} title="Chỉ báo"><Settings2 size={18}/></button></div>
  <div className="chart-heading"><div><div className="title-line"><strong>{symbol}</strong><span>{market==="spot"?'Spot':'Futures USDⓈ-M'}</span><span className="muted">·</span><span className="muted">{interval}</span></div><div className="ohlc">{shown?<><span>O <b>{shown.open.toLocaleString('en-US')}</b></span><span>H <b>{shown.high.toLocaleString('en-US')}</b></span><span>L <b>{shown.low.toLocaleString('en-US')}</b></span><span>C <b className={shown.close>=shown.open?'up':'down'}>{shown.close.toLocaleString('en-US')}</b></span><span>V <b>{shown.volume.toLocaleString('en-US',{maximumFractionDigits:2})}</b></span></>:"Đang lấy dữ liệu Binance…"}</div></div><span className="source-note">Nguồn: Binance · UTC</span></div>
  <div className="chart-area">{error&&<div className="chart-error"><WifiOff size={17}/>{error}<button onClick={()=>window.location.reload()}><RefreshCw size={15}/></button></div>}<CandleChart bars={bars} enabled={enabled} formula={formula} onNeedHistory={more} onHover={setHover}/></div>
  <div className="chart-footer"><span>Kéo để xem lịch sử · Lăn chuột để zoom · Di chuột xem OHLCV</span><span>{bars.length} nến · Nến cuối có thể chưa đóng</span></div></section>
  <aside className="side-panel"><div className="panel-tabs"><button className={panel==="indicators"?'active':''} onClick={()=>setPanel("indicators")} title="Chỉ báo"><Activity size={18}/></button><button className={panel==="editor"?'active':''} onClick={()=>setPanel("editor")} title="Pine Script"><Code2 size={18}/></button>{me?.role==="admin"&&<button className={panel==="access"?'active':''} onClick={()=>setPanel("access")} title="Quyền truy cập"><Shield size={18}/></button>}<button className={panel==="help"?'active':''} onClick={()=>setPanel("help")} title="Hướng dẫn"><CircleHelp size={18}/></button></div>
   {panel==="indicators"&&<div className="panel-content"><div className="panel-eyebrow">PHÂN TÍCH</div><h2>Chỉ báo</h2><p className="subtext">Bật chỉ báo để hiển thị ngay trên biểu đồ.</p><div className="indicator-list">{PALETTE.map(item=><button className={'indicator-row '+(enabled[item.key]?'is-on':'')} key={item.key} onClick={()=>toggle(item.key)}><span className="indicator-mark" style={{background:item.color}}/><span className="indicator-copy"><strong>{item.title}</strong><small>{item.detail}</small></span><span className="switch"><i/></span></button>)}</div><div className="panel-subhead">CHỈ BÁO CỦA TÔI <button onClick={()=>{setScriptId(null);setScriptName("Chỉ báo của tôi");setSource(SAMPLE);setPanel("editor")}}>+ Tạo mới</button></div>{scripts.length? scripts.map(s=><button key={s.id} className={'saved-script '+(s.id===activeScript?'is-active':'')} onClick={()=>{setScriptId(s.id);setScriptName(s.name);setSource(s.source);setPanel("editor")}}><Code2 size={16}/><span>{s.name}</span><ChevronDown size={13}/></button>):<p className="empty">Chưa có chỉ báo tùy chỉnh.</p>}{formula&&<button className="text-action" onClick={()=>{setFormula(null);setActiveScript(null)}}>Ẩn chỉ báo tùy chỉnh đang áp dụng</button>}</div>}
   {panel==="editor"&&<div className="panel-content editor"><div className="panel-eyebrow">PINE SCRIPT · TẬP CON</div><h2>Chỉ báo của tôi</h2><p className="subtext">Dán mã Pine đơn giản hoặc viết một lệnh plot. Lệnh chưa hỗ trợ sẽ được báo rõ.</p><label className="field-label">Tên chỉ báo</label><Input value={scriptName} onChange={e=>setScriptName(e.target.value)} maxLength={80}/><label className="field-label">Mã chỉ báo</label><textarea className="code-area" spellCheck={false} value={source} onChange={e=>setSource(e.target.value)} aria-label="Mã Pine Script"/><p className="code-tip">Hỗ trợ: Pine v5/v6, indicator(), input.int/float(), một plot() với close/open/high/low/volume hoặc ta.sma, ta.ema, ta.rsi, ta.stdev. Không hỗ trợ strategy, request.security, nhiều plot và thư viện import.</p><div className="editor-actions"><Button onClick={save}>Lưu & áp dụng</Button><Button variant="outline" onClick={apply}>Thử trên biểu đồ</Button></div>{scriptId&&<button className="delete-action" onClick={remove}>Xóa chỉ báo này</button>}</div>}
   {panel==="access"&&<div className="panel-content"><div className="panel-eyebrow">QUẢN LÝ</div><h2>Người được mời</h2><p className="subtext">Mỗi người có vùng lưu chỉ báo riêng.</p><label className="field-label">Email tài khoản ChatGPT</label><div className="invite-row"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ten@example.com"/><Button onClick={addInvite}>Thêm</Button></div><p className="access-note">Danh sách này chỉ cấp quyền trong ứng dụng. Bạn cũng cần chia sẻ Site cho email này trong phần Chia sẻ của Sites. Thu hồi quyền ở cả hai nơi.</p>{invites.map(i=><div className="invite-item" key={i.email}><span>{i.email}</span><button onClick={async()=>{try{await api({action:"revoke",email:i.email});setInvites(x=>x.filter(v=>v.email!==i.email))}catch(e){flash((e as Error).message)}}} title="Thu hồi trong ứng dụng"><X size={15}/></button></div>)}</div>}
   {panel==="help"&&<div className="panel-content"><div className="panel-eyebrow">HƯỚNG DẪN</div><h2>Cách sử dụng</h2><p className="subtext">Biểu đồ hiển thị dữ liệu công khai của Binance, không cần khóa API.</p><ul className="help-list"><li>Nhập cặp như BTCUSDT rồi nhấn Enter.</li><li>Kéo để xem lịch sử; cuộn chuột để zoom. Nến cũ được tải thêm khi kéo sát mép trái.</li><li>Chọn Spot hoặc Futures USDⓈ-M và khung thời gian ở thanh trên.</li><li>Mở biểu tượng mã để dán Pine Script; thử và lưu khi mã hợp lệ.</li></ul><div className="limit-box"><strong>Giới hạn hiện tại</strong><p>Hỗ trợ một tập con Pine Script, không chạy được mọi script TradingView. Luồng WebSocket kết nối trực tiếp từ trình duyệt đến Binance; khi lỗi sẽ đồng bộ bằng truy vấn định kỳ. Futures ở đây là USDⓈ-M.</p></div></div>}
   <div className="panel-bottom">CHARTLAB <span>·</span> dữ liệu Binance<br/>TradingView Lightweight Charts™ · Copyright © 2025 <a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">TradingView, Inc.</a></div></aside></div>{notice&&<div className="toast" role="status">{notice}</div>}
 </main>
}
